export enum TransactionType {
  BUY = 'BUY',
  SELL = 'SELL',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}

export enum StrategyType {
  AUTO_INVEST = 'AUTO_INVEST',
  TAKE_PROFIT = 'TAKE_PROFIT',
  STOP_LOSS = 'STOP_LOSS',
  GRID_TRADING = 'GRID_TRADING',
  REBALANCE = 'REBALANCE',
}

export enum InvestFrequency {
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
}

export enum RiskLimitType {
  DAILY_TRADE_LIMIT = 'DAILY_TRADE_LIMIT',
  SINGLE_TRADE_LIMIT = 'SINGLE_TRADE_LIMIT',
  DAILY_TRADE_COUNT_LIMIT = 'DAILY_TRADE_COUNT_LIMIT',
  POSITION_RATIO_LIMIT = 'POSITION_RATIO_LIMIT',
  MAX_DRAWDOWN_LIMIT = 'MAX_DRAWDOWN_LIMIT',
  TOTAL_ASSET_STOP_LOSS = 'TOTAL_ASSET_STOP_LOSS',
}

export enum BlacklistType {
  FUND_CODE = 'FUND_CODE',
  FUND_MANAGER = 'FUND_MANAGER',
  FUND_COMPANY = 'FUND_COMPANY',
}

export enum BlacklistReason {
  POOR_PERFORMANCE = 'POOR_PERFORMANCE',
  MANAGER_CHANGE = 'MANAGER_CHANGE',
  INAPPROPRIATE_SIZE = 'INAPPROPRIATE_SIZE',
  STYLE_DRIFT = 'STYLE_DRIFT',
  HIGH_RISK_INDUSTRY = 'HIGH_RISK_INDUSTRY',
  REGULATORY_PENALTY = 'REGULATORY_PENALTY',
  LIQUIDITY_RISK = 'LIQUIDITY_RISK',
  OTHER = 'OTHER',
}
