export enum TransactionType {
  BUY = 'BUY',
  SELL = 'SELL',
}

export enum TransactionStatus {
  CREATED = 'CREATED',
  PENDING_SUBMIT = 'PENDING_SUBMIT',
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum StrategyType {
  AUTO_INVEST = 'AUTO_INVEST',
  TAKE_PROFIT_STOP_LOSS = 'TAKE_PROFIT_STOP_LOSS',
  GRID_TRADING = 'GRID_TRADING',
  REBALANCE = 'REBALANCE',
}

export enum InvestFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum RiskLimitType {
  DAILY_TRADE_LIMIT = 'DAILY_TRADE_LIMIT',
  SINGLE_TRADE_LIMIT = 'SINGLE_TRADE_LIMIT',
  DAILY_TRADE_COUNT_LIMIT = 'DAILY_TRADE_COUNT_LIMIT',
  POSITION_RATIO_LIMIT = 'POSITION_RATIO_LIMIT',
  MAX_DRAWDOWN_LIMIT = 'MAX_DRAWDOWN_LIMIT',
  TOTAL_ASSET_STOP_LOSS = 'TOTAL_ASSET_STOP_LOSS',
  SINGLE_TRADE_CONFIRM_THRESHOLD = 'SINGLE_TRADE_CONFIRM_THRESHOLD',
}

/**
 * 交易确认状态枚举
 *
 * 用于大额交易确认流程，防止误操作导致的重大损失。
 *
 * 状态流转：
 * PENDING_CONFIRMATION -> CONFIRMED（用户确认）
 * PENDING_CONFIRMATION -> CANCELLED（用户手动取消）
 * PENDING_CONFIRMATION -> TIMEOUT_CANCELLED（超时自动取消）
 */
export enum TransactionConfirmationStatus {
  /** 等待确认 */
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  /** 已确认 */
  CONFIRMED = 'CONFIRMED',
  /** 已取消（用户手动） */
  CANCELLED = 'CANCELLED',
  /** 超时取消 */
  TIMEOUT_CANCELLED = 'TIMEOUT_CANCELLED',
}

export enum BlacklistType {
  FUND_CODE = 'FUND_CODE',
  FUND_MANAGER = 'FUND_MANAGER',
  FUND_COMPANY = 'FUND_COMPANY',
}

export enum BlacklistReason {
  POOR_PERFORMANCE = 'POOR_PERFORMANCE',
  MANAGER_CHANGE = 'MANAGER_CHANGE',
  INAPPROPRIATE_SIZE = 'INAPPROPRIATE_SIZE',
  STYLE_DRIFT = 'STYLE_DRIFT',
  HIGH_RISK_INDUSTRY = 'HIGH_RISK_INDUSTRY',
  REGULATORY_PENALTY = 'REGULATORY_PENALTY',
  LIQUIDITY_RISK = 'LIQUIDITY_RISK',
  OTHER = 'OTHER',
}
